sed -i '' 's/勿/弗/g' wuu-wiki.txt
sed -i '' 's/佢/伊/g' wuu-wiki.txt
sed -i '' 's/渠/伊/g' wuu-wiki.txt
sed -i '' 's/无没/呒没/g' wuu-wiki.txt
sed -i '' 's/无啥/呒啥/g' wuu-wiki.txt
sed -i '' 's/无得/呒得/g' wuu-wiki.txt
sed -i '' 's/乃么/乃末/g' wuu-wiki.txt
sed -i '' 's/个末/葛末/g' wuu-wiki.txt
sed -i '' 's/里厢/里向/g' wuu-wiki.txt
sed -i '' 's/来垃/勒拉/g' wuu-wiki.txt
sed -i '' 's/来拉/勒拉/g' wuu-wiki.txt
sed -i '' 's/来里/勒里/g' wuu-wiki.txt
sed -i '' 's/辣辣/勒拉/g' wuu-wiki.txt
sed -i '' 's/垃拉/勒拉/g' wuu-wiki.txt
sed -i '' 's/拉垃/勒拉/g' wuu-wiki.txt
sed -i '' 's/了垃/勒拉/g' wuu-wiki.txt
sed -i '' 's/了拉/勒拉/g' wuu-wiki.txt
sed -i '' 's/勒垃/勒拉/g' wuu-wiki.txt